port: 3000
host: "localhost"
uploads:
  driver: "s3"
  #local:
  #  path: "./uploads"
  s3:
    bucket: "wiki-de"
    region: "us-east-1"
    baseUrl: "http://20.113.157.181:9000"
    keyPrefix: "/"
    accessKeyId: "adminminio"
    secretAccessKey: "Ks6srBRA-Qd57nW"
frontend:
  title: "Knowledgehub [DE]"
  description: "Das deutschsprachige Wiki des B+G Knowledgehubs"
  startPage: ""
  misprintsChatId: "12344564"
  yandexMetrikaId: ""
  carbon:
    serve: ""
    placement: ""
  menu:
    - "Guides"
    - title: "Bollinger+Grohmann"
      uri: "https://bollinger-grohmann.com"

auth:
  password: secretpassword
  secret: supersecret

hawk:
#  frontendToken: "123"
#  backendToken: "123"

database:
  driver: mongodb # you can change database driver here. 'mongodb' or 'local'
#  local:
#    path: ./db
  mongodb:
    uri: mongodb+srv://ahofbeck:yZtvVQ8P..Szu99@cluster0.qu5ee.mongodb.net/wiki-de
